### PR TITLE
Update build script

### PR DESCRIPTION
**Pull request by alphp**
Upgrading build script to use the new php-sdk OSTC/php-sdk-binary-tools #12
* YAML AppVeyor: Simplified, added new environment variables.
* Install Script (install.cmd): New, prepare the build environment
* Build Script (build.cmd): Simplified, sets the environment variables for each Architecture.
* Build Task Script (build_task.cmd): New, build the TS and NTS versions for each Architecture.
* Added new artifacts, each binary of the extensión, LICENSE file and examples are packaged as separate zip for each version (PHP release, Architecture and TS/NTS).

### CODE REVIEW

**Comment by macintoshplus** [comment]
The new php-sdk is official ?
I don't found this into the official documentations.

**Comment by alphp** [comment]
Not yet, but the [php/src-src](/php/php-src) repository uses it in its [AppVeyor build script](https://github.com/php/php-src/blob/master/appveyor/build.bat).
On the other hand the php-sdk tools do not influence the build itself.

**Comment by alphp** [comment]
http://externals.io/thread/432#email-12770
http://news.php.net/php.windows/31430
http://news.php.net/php.windows/31431
http://news.php.net/php.internals.win/1138

**Comment by macintoshplus** [comment]
Good news. This change is for `php7` branch but it's also usable for the branch `php7-cli` ?

**Comment by alphp** [comment]
Yes, is for both branches...

**Pull request merged**
