### PR TITLE
Fix issue with PHP 7.1.4

### PR DESCRIPTION
**Pull request by alphp**
- Fix issue with PHP 7.1.4: Not detect PHP RELEASE VERSION correctly
- Update .appveyor.yml: change SDK BRANCH to master

### CODE REVIEW

**Comment by macintoshplus** [comment]
Hi,
The Artefacts build for this PR work fine ?

**Comment by alphp** [comment]
Sorry for the delay in responding.
I have not performed a complete test, just the basic load of the extension.
Next week I will do the relevant tests.

**Comment by alphp** [comment]
I have proceeded with the tests through service.php and everything works correctly.
I have tried with PHP-7.1.4-ts-x64, but as the only line of code that has been changed only affects the load the extension should work correctly with all other variants (ts, nts, x86, x64) .

**Comment by alphp** [comment]
Binaries to test:
https://ci.appveyor.com/project/alphp/win32service/branch/php7

**Comment by alphp** [comment]
In IS #11 @AnrDaemon says:

> It is a building issue, PECL maintainer used PHP Version: 7.1.0 to build extension.
> See http://windows.php.net/downloads/pecl/releases/win32service/0.2.0/logs/php_win32service-0.2.0-7.1-ts-vc14-x64-logs.zip

I have tested the release 2.0.0 binaries and they work correctly, it's the PECL binaries that are built with the wrong version of PHP.

**Comment by Jan-E** [comment]
> I have tested the release 2.0.0 binaries and they work correctly, it's the PECL binaries that are built with the wrong version of PHP.

PECL binaries will be rebuilt with the current PHP 7.0 & PHP 7.1 at a new release of the extension or by pinging the PECL maintainers. If you merge this PR, I will ping them.

**Comment by macintoshplus** [comment]
Thanks for you very great job.

I wait end of build from AppVeyor for upload the artefact on github release v0.2.1 and I update the PECL ext ASAP.

**Comment by macintoshplus** [comment]
@Jan-E The PECL package is now up to date.

**Pull request merged**
