### PR TITLE
Added stub lib for IDEs to auto-complete this extension's functions/constants.

### PR DESCRIPTION
**Pull request by credomane**
Two useful files for IDE's that enable auto-complete features for functions and constants provided by php_win32service.

[edit]
I found PhpStorm always complaining about missing functions/constants annoying. Had this added to a global include in PhpStorm for a couple years now. Hopefully these are useful to other people too. I never did push these to my unofficial win32service repo for some reason.

### CODE REVIEW

**Comment by macintoshplus** [comment]
i don't understand the interest to add this pseudo code into the ext's repository. This is specially for one IDE and and don't add any functionality into the extension.

You can share this in a gist.github.com and add a link into the extension's readme for share ?

Thank's for you work.

**Comment by credomane** [comment]
Sure I can that. Positive any PHP IDE with auto-complete could use these files without issue. I just figured it would be more elegant/official this way.

**Comment by macintoshplus** [comment]
Okay, have-you any idea where I set this code in this extension ? Into a ide-auto-complete folder ?

For deployed this code, it's needed to add this file into the PECL package.

**Comment by macintoshplus** [comment]
There files will be distributed in the new library for Win32service.

See: https://github.com/win32service/win32servicelib

**Pull request closed without merging**
